---
name: "Build, release and publish"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "macos-latest"
    
    steps:
    # python3.7
    - uses: actions/checkout@v3
    - name: Set up Python (Python 3.7)
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install dependencies (Python 3.7)
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package (Python 3.7)
      run: python -m build
    # end build
    # python3.8
    - name: Set up Python (Python 3.8)
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies (Python 3.8)
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package (Python 3.8)
      run: python -m build
    # end build
    # python3.9
    - name: Set up Python (Python 3.9)
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies (Python 3.9)
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package (Python 3.9)
      run: python -m build
    # end build
    # python3.10
    - name: Set up Python (Python 3.10)
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies (Python 3.10)
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package (Python 3.10)
      run: python -m build
    # end build
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.OWNER_GH_API_TOKEN }}"
        prerelease: false
        files: dist/*    
       
  tagged-publish:
    name: "Tagged Publish"
    runs-on: "ubuntu-latest"
    
    steps:
    - uses: robinraju/release-downloader@v1.7
      with:
        latest: true
        fileName: "*"
        out-file-path: "dist"
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}