---
name: "Publish"
on: [push]

jobs:
  tagged-publish:
    name: "Tagged Publish"
    runs-on: "ubuntu-latest"
    
    steps:
    - uses: robinraju/release-downloader@v1.7
      with:
        latest: true
        fileName: "*"
        out-file-path: "dist"
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}